name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: actions/cache@v4
        id: node-modules
        with:
          path: |
            node_modules/
            .next/cache/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Build
        run: |
          pnpm install
          pnpm build
      - uses: actions/upload-artifact@v4
        with:
          path: out/
  deploy:
    needs: build
    uses: NKID00/nkid00.name/.github/workflows/deploy.yml@master
    secrets: inherit
