name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve current time
        run: |
          echo "TIME=$(date --iso-8601=seconds --utc)" >> ${GITHUB_ENV}
      - name: Configure git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: actions/cache@v4
        id: node-modules
        with:
          path: |
            node_modules/
            .next/cache/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Build
        run: |
          pnpm install
          pnpm build
      - name: Create release
        run: |
          gh release delete release --cleanup-tag -y || true
          git tag release
          git push origin --tags
          pushd out
          zip -qr ../dist.zip *
          popd
          gh release create release --latest -n "${{ env.TIME }}" dist.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build
    uses: NKID00/nkid00.name/.github/workflows/deploy.yml@master
    secrets: inherit
